import { test, expect } from '../../../../../../fixtures/self-healing';

test('register', async ({ page }) => {
  // Generated by AI Agent
  
  // Navigate to Parabank login page
  await page.goto('https://parabank.parasoft.com/parabank/index.htm?ConnType=JDBC');

  // Click on Register link
  await page.getByRole('link', { name: 'Register' }).click();

  // Enter username
  await page.locator('input[name="username"]').first().fill('testuser123');

  // Enter password
  await page.locator('input[name="password"]').first().fill('Testpass123!');

  // Confirm password
  await page.locator('input[name="repeatedPassword"]').first().fill('Testpass123!');

  // Enter first name
  await page.locator('input[name="customer.firstName"]').first().fill('Test');

  // Enter last name
  await page.locator('input[name="customer.lastName"]').first().fill('User');

  // Enter street address
  await page.locator('input[name="customer.address.street"]').first().fill('123 Main St');

  // Enter city
  await page.locator('input[name="customer.address.city"]').first().fill('Springfield');

  // Enter state
  await page.locator('input[name="customer.address.state"]').first().fill('IL');

  // Enter zip code
  await page.locator('input[name="customer.address.zipCode"]').first().fill('62701');

  // Enter phone number
  await page.locator('input[name="customer.phoneNumber"]').first().fill('555-1234');

  // Enter SSN
  await page.locator('input[name="customer.ssn"]').first().fill('123-45-6789');

  // Click Register button to complete registration
  await page.getByRole('button', { name: 'Register' }).click();

  // Enter username for login
  await page.locator('input[name="username"]').first().fill('testuser123');

  // Enter password for login
  await page.locator('input[name="password"]').first().fill('Testpass123!');

  // Click Login button
  await page.getByRole('button', { name: 'Log In' }).click();
});
